title: Pete's Sites!
author: PeteGhost
email: pete@petesites.com
description: > # this means to ignore newlines until "baseurl:"
  This will be my main site where I will showcase all the 
  projects I currently have going on. Be it code, design,
  art, music or even photography.
theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
